### ISSUE TITLE
Wrong silk mask text

### ISSUE THREAD

**Issue by BoguslavskyiR** [PricelessToolkit/SOILSENS-V5W#10]
During flashing first board was discovered that UART contacts have wrond naming

![image](https://github.com/user-attachments/assets/acc5ecf7-12f4-4d8c-982a-658285384ad3)

**Comment by PricelessToolkit** [comment]
Strange. Are you sure that the pinout name on your programmer is correct? 

TP4 is TX and it is current.
 https://github.com/PricelessToolkit/SOILSENS-V5W/blob/main/PCB/Soilsens-V5W_Schematic.jpg

**Comment by BoguslavskyiR** [comment]
I will double check, but it's not the first time I have used this adapter (DFrobot dfr0065).
But i will check again with another adapter

**Comment by PricelessToolkit** [comment]
![ftdi](https://github.com/user-attachments/assets/f6eee354-b22c-45fc-94c8-64ba904305c6)

**Comment by BoguslavskyiR** [comment]
In this case sorry, but it's very strange, I've been using this dongle for a long time with the rx->tx connection.

**Comment by PricelessToolkit** [comment]
No need to apologize! It's all good I’m here for help. If you want to check it yourself, just snap a photo, zoom in, and follow the PCB trace from pin 5. Unfortunately, I couldn’t find a high-quality photo, but this one is the best I’ve seen so far:
https://m.media-amazon.com/images/I/6115v8bCfbL._AC_SL1000_.jpg
