### ISSUE TITLE
kicad files missing

### ISSUE THREAD

**Issue by shufps** [PricelessToolkit/SOILSENS-V5W#3]
It seems there are no KiCad files in the repository.

**Comment by PricelessToolkit** [comment]
I don't share KiCad files; only Gerber files and the BOM are provided for self-assembly.

**Comment by shufps** [comment]
Why not?

"Copy protection" doesn't make sense because I can replicate your entire KiCad project from your schematic and pictures on a single day.

It's just annoying having to do this but it actually doesn't protect anything by not publishing it :thinking:

**Comment by PricelessToolkit** [comment]
1. It protects from generating a 'PnP placement file' and from logo swappers. 2. I’d rather not have to explain my routing choices every two minutes or hear critiques on how it 'should' be done, one or two suggestions per project are fine, but every passerby seems to have a new idea, and I simply don’t have the time. I share the Gerbers for the Home Assistant community, so if someone prefers not to buy the assembled version, they can assemble it themselves as a more affordable option.
