### ISSUE TITLE
MQTT auto-discovery not working with Capibridge 

### ISSUE THREAD

**Issue by ppkstat** [PricelessToolkit/SOILSENS-V5W#8]
I just finished building my Soilsens. The device appears to function correctly but it is not discovered by MQTT in home assistant. 
This is what is beeing received by the Capibridge when triggered: 
ESP-NOW Message: {"k":"xy","id":"Soilsens Autopot ","b":65,"l":26,"mo":0,"t":18,"t2":18,"hu":54}

and this is a screenshot of the MQTT explorer: 
![soilmqtt](https://github.com/user-attachments/assets/da273199-982a-424b-bec0-273854ef6ca5)

**Comment by PricelessToolkit** [comment]
1. Is your Capibridge key "xy"? , make sure that capibridge and soilsens has the same key.
2. "Soilsens Autopot " remove spaces, from the middle and from the end "Soilsens-Autopot" I will add this in the manual!
